### ISSUE TITLE
 OSX or Linux, it is highly recommended you use NFS as the Shared Folder Type

### ISSUE THREAD

**Issue by justinpage** [wpengine/hgv#115]
It is highly recommended that users who are on OSX or Linux, use NFS as shared folder type. This is a common practice in vagrant environments. 

We should either prerequisite or highly recommend vagrant-bindfs plugin: 
- `$ vagrant plugin install vagrant-bindfs.`

The provisioner will default to this shared folder type but describing this plugin specific will ease the on-boarding process.

**Comment by zamoose** [comment]
@KLVTZ:
I've seen various conflicting statements on this one. Do you have a definitive source for the recommendation?

**Comment by KLVTZ** [comment]
@zamoose I base this on two different projects and their recommendations. 

If we take a look at [vagrant-bindfs/readme.md](https://github.com/gael-ian/vagrant-bindfs/blob/master/README.md), there is some background on `bindfs`. More specifically, it fixes the issue of setting correct permission. This is due to the default nature of how NFS works on OSX. Plus, there is a performance gain as described in [vagrant nfs docs](http://docs.vagrantup.com/v2/synced-folders/nfs.html).

The other recommendation comes from [vagrant/puphpet](https://puphpet.com/). This is a very popular online GUI for generating your provisioner script. If we scroll to the bottom we will notice under "Sharing Folders with Local VM" that `bindfs` is again recommended. This has fixed common issues under this environment by using the [vagrant plugin](https://github.com/puphpet/puphpet/issues/334).

One last thing I'll mention is that since I have `bindfs` installed on my machine, I do notice that it defaults to that config. I'm not sure if this is a result from ansible or not but I thought I share this.
