### ISSUE TITLE
Should we put nginx configs in conf.d/ ?

### ISSUE THREAD

**Issue by markkelnar** [wpengine/hgv#14]
Package dependencies have changed between nginx 1.4.6 -> 1.6. Looks like nginx (since nginx-common is no longer required), does not provide or require the /etc/nginx/sites-available/sites-enabled directories. Nginx.conf is configured to load /etc/nginx/conf.d/ instead.

Might be more straightforward if we put the configs in conf.d/ instead of trying to create and mimic the apache style sites-available/enabled model if Nginx stopped doing that. But not functionally much different.

**Comment by wp-michael** [comment]
Looking over the nginx source in their Trac repo, I don't see that it ever had those paths.
This is probably something that debian/ubuntu layered over it. I know the 1.4.6 that gets installed on my host includes those paths as part of the nginx.conf. You could choose to add any back in or just use what's there.

Based on what I have read, 
conf.d - module loading and more global stuffs
sites-enabled/sites-available - site configurations

That's just kind of a guideline though. The sites-enabled are a handy way to enable/disable sites by messing with symlinks rather than files.

**Comment by zamoose** [comment]
This was completed in #71.
