### ISSUE TITLE
Add Xdebug helper Chrome Extension to docs

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#166]
Document [Xdebug helper](https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc?hl=en) as a useful way to enable/disable Xdebug.

**Comment by michaelbeil** [comment]
What a great resource @zamoose.

**Comment by jb510** [comment]
Xdebug browser extensions to toggle Xdebug on/off without having to ssh into the virtual machine:
Safari: https://github.com/benmatselby/xdebug-toggler
FireFox: https://addons.mozilla.org/en-US/firefox/addon/the-easiest-xdebug/
Chrome: https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc

Also note: I'm not entirely clear from the current documentation which says "xdebug is enabled by default" if "xdebug is on" or just "xdebug is installed" by default. IIRC on by default is a bad idea because it does cause a pretty big performance hit.

**Comment by zamoose** [comment]
It's installed, not enabled by default. *grin* 




Thanks for the links!



—
Doug
