### ISSUE TITLE
Alternative to php/hhvm being separate sub-domains

### ISSUE THREAD

**Issue by jb510** [wpengine/hgv#182]
Just curious if controlling php vs hhvm by other means that would allow them to use the same URL was ever considered?

Something like toggling xdebug/profile on/off?

I'm ignorant of the inner workings so I don't know if this makes any sense at all, but generally I wish I could use: lcl.domain.com and have it running on hhvm by default, than if/when I wanted to I could toggle it with something like lcl.domain.com/?engine=php and it'd start running on php.

Maybe not as "in your face" as sub-domain names, but most of the time I don't need php/hhvm at the same time.

or if the .com in there throws you (I think I'm the only person on the planet that does it lcl.domain.com) then domain.dev/?engine=php and domain.dev/?engine=hhvm to toggle.

**Comment by markkelnar** [comment]
Thanks for the question.  We entertained something like that during early designs.  It's not impossible to do but not ideal.  The logic to determine the backend is the domain + a Nginx variable/header.  

One idea is to add change the domain that is 'mapped' to the backend service.  Meaning, lcl.domain.com is set up to send requests to HHVM.  When you want to change that, you change the Nginx config to send to PHP.  Maybe you do that manually, or in a dashboard or in the config file than vagrant provision.

Another idea was to use an nginx failover when the HHVM service is not available.  You'd turn off the HHVM service/process, then let Nginx try the request with PHP-FPM.  We didn't like that idea, because one primary point of developing in HGV is to test against HHVM and when that code breaks when run by HHVM or HHVM stops running, it'll be obvious with an error.  Then you point at the PHP domain to see if it's broken PHP or something that is not compatible with the HHVM compiler.

And yet another idea is to add a cookie that gets set and passed in for all page requests.

It would probably be something like this:
1) Pass in a toggle, like you proposed
2) A cookie gets passed to the client/browser with the value hhvm or php.
3) Nginx sees the cookie value and uses that to determine the backend to use.

Is there something in your process, code or database that makes it difficult to use another domain to point at PHP?  Trying to understand more in case you're not the only one with a workflow that limits this use or functionality.

**Comment by jb510** [comment]
Thanks for the detailed explanation Mark. I never doubted it well well reasoned and that all makes a lot of sense.

As for my workflow it was really about being more similar to my existing workflow.  The point about needing to fall back to php for debugging when hhvm fails is a great one though I hadn't sufficiently considered.  I think I'll just start setting lcl.domain.com to run hhvm, then leave php.domain.com as a fallback.  (FWIW, my restience to that was that lcl.domain.com for me always meant VVV, but I'm over that).  I might also finally give up on my preference for lcl. instead of .dev (which is because domain auto-complete works beautifully that way)

Thanks again for the detailed explanation!

**Comment by zamoose** [comment]
Mark:
Funny you mentioned cookies -- that's what I was going to suggest, a la the
Xdebug on/off setup.

But yes, complicated.

On Wed, Jun 24, 2015 at 1:35 PM, Mark Kelnar <notifications@github.com>
wrote:

> Thanks for the question. We entertained something like that during early
> designs. It's not impossible to do but not ideal. The logic to determine
> the backend is the domain + a Nginx variable/header.
>
> One idea is to add change the domain that is 'mapped' to the backend
> service. Meaning, lcl.domain.com is set up to send requests to HHVM. When
> you want to change that, you change the Nginx config to send to PHP. Maybe
> you do that manually, or in a dashboard or in the config file than vagrant
> provision.
>
> Another idea was to use an nginx failover when the HHVM service is not
> available. You'd turn off the HHVM service/process, then let Nginx try the
> request with PHP-FPM. We didn't like that idea, because one primary point
> of developing in HGV is to test against HHVM and when that code breaks when
> run by HHVM or HHVM stops running, it'll be obvious with an error. Then you
> point at the PHP domain to see if it's broken PHP or something that is not
> compatible with the HHVM compiler.
>
> And yet another idea is to add a cookie that gets set and passed in for
> all page requests.
>
> It would probably be something like this:
> 1) Pass in a toggle, like you proposed
> 2) A cookie gets passed to the client/browser with the value hhvm or php.
> 3) Nginx sees the cookie value and uses that to determine the backend to
> use.
>
> Is there something in your process, code or database that makes it
> difficult to use another domain to point at PHP? Trying to understand more
> in case you're not the only one with a workflow that limits this use or
> functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/issues/182#issuecomment-114949915>.
>



-- 
-Doug

**Comment by markkelnar** [comment]
:)  I think I'm going to put this in the FAQ wiki too for future reference to explain some of design decision.

**Comment by markkelnar** [comment]
Added here.  I'll close this issue.  It can be reopened if it's got something in it we should put on the todo work list.

**Comment by markkelnar** [comment]
I reopened this original issue because it became apparent that testing multisite WP on each backend became complicated or impossible when done just by domain.

The preposed code change would add support for a cookie called 'backend'.  In the future, if there's demand, we can provide a way for users to specify and control their own cookie name.  Seemed unimportant at the immediate moment.  

Other than that, does this proposed code look like it will do the job?
