### ISSUE TITLE
Document Windows Provisioning for cross platform dev 

### ISSUE THREAD

**Issue by stephen-lin** [wpengine/hgv#194]
Document how to resolve provisioning failures when Windows machines handle line endings incorrectly when cloning projects from Linux.

#193

**Comment by nicoladj77** [comment]
I will leave my experience on setting up hgv on Windows 7

- Errors in setting up port forwarding - solved by updating to powershell 3
- Process [hanging](http://stackoverflow.com/questions/25013526/vagrant-hangs-on-windows-7) after a call to powershell - solved by [updating powershell](http://www.microsoft.com/en-us/download/details.aspx?id=34595)
- Errors when mounting smb share - fixed by creating a new user in windows and [sharing with it](https://github.com/mitchellh/vagrant/issues/4823#issuecomment-82345425)

**Comment by ericmann** [comment]
Added Windows troubleshooting to the Wiki: https://github.com/wpengine/hgv/wiki/Troubleshooting#im-having-issues-getting-vagrant-to-provision-hgv-for-me-also-im-running-windows-
