### ISSUE TITLE
Allow overrides to the Vagrant configuration, similar to VVV

### ISSUE THREAD

**Issue by JPry** [wpengine/hgv#197]
VVV has had the ability for some time now to create a file named `Customfile`. This file will be parsed by the Vagrantfile as Ruby, and allows for overriding some of the default configurations.

For example, placing the following code into the `Customfile` will configure the VVV Vagrant with public networking, without the need to modify the `Vagrantfile` directly:

```ruby
  # Set up with a Public network
  config.vm.network :public_network
```

It would be nice to see something similar in hgv, and even better if it could somehow be implemented in a YAML file instead of a Ruby file. The YAML file could be in a pre-defined location, such as `hgv_data/config/vagrant/custom.yml`.

I'm not well-versed enough in Ruby to know exactly how to go about doing the YAML implementation that I described above, otherwise I would submit a PR.

On a related note, it might make more sense to divide the the `hgv_data/config/` directory into sub-directories, instead of *only* having site files there. Maybe something like this:

```
+ hgv_data/
|      + config/
|      |      + sites/
|      |      |      foo.yml
|      |      |      bar.yml
|      |      + vagrant/
|      |      |      custom.yml
```

**Comment by markkelnar** [comment]
Thanks @JPry 

I too have thought that we might need more sophistication around the layout and naming convention of things under the config/ directory.  And do it before we get too far down the road.  

The CustomFile thing is interesting and definitely an advanced user feature.  At minimal, adding the support for something like that would make fixing on-off issues for people more 'pluggable'.  Especially for things that aren't ready to be added to the default VagrantFile or things that are OS specific, etc.

**Comment by ericmann** [comment]
As much as I'd love to move from Ruby to a Yaml file (it's easier to configure), that will be a much bigger change than just adding support for a VVV-style `Customfile`. Since that file is included directly, it can run Ruby code to both modify settings _and_ include additional logic.

This has come into play on some systems (i.e. Windows) when needing to program in custom logic for file shares or dynamically-attributed network addresses.

So I'm all for a `Customfile`, but I think a first version should stick with the VVV style of a Ruby include. A Yaml file would be great, but might limit us too much.
