### ISSUE TITLE
wpengine supporting composer

### ISSUE THREAD

**Issue by KLVTZ** [wpengine/hgv#206]
> A message to the wpengine internal devs. Not an hgv issue.

Let's face it, this is one feature that wpengine needs to support if wordpress is going to move forward on this platform. The importance of package management and it's implementation have been widely accepted and implemented by your competitors.

It seems any technical representative that I talk to says the same thing: it is currently not supported. Now they do preempt this with "we might consider this in the future". But when is the future? I know I'm not the only developer that has tweeted wpengine asking for this. And I know I'm not the first to provide a workaround through versioning composer as a binary for autoloading support (costing major deltas in git).

I'm not going to ignore the huge challenges this may face. One possible blocker in argument is public/private keys via SSH: http://wpengine.com/git/#toc_8. But has this not been solved by other providers? I've also heard mentioned that wpengine has too many things in the pipeline that outweigh this feature. More dialogue would be great to help us understand the reasons.

All in all, my only hope is you guys. I can only ask that somehow you spark a fire. Always stressing the importance of this item.

**Comment by markkelnar** [comment]
Thanks for the @KLVTZ.  I appreciate your thoughts and feedback about the GitPush workflow. And although this is not an inlet for all things related to the WP Engine stack, I consider it to be related to the expected workflow and development environment that HGV is striving to become.  And as we add more features and hooks to HGV, such as ‘vagrant push’ and connections with our Git endpoints, we desire more adoption of HGV as the tool of choice for WP development for WP Engine customer and even non-customers.

I’ve made a personal commitment to continue to grow HGV with the appropriate tools and integration with the WP Engine platform.  And in order to do that, we have to spend time on and enhance the GitPush application on our endpoint.  

I've had recent conversations with the team about this exact issue with composer in our environment and walked away with ideas about implementing this in our workflow.  So, please bare with us.  As a Labs team project, we may even be able to tackle this feature as a thing and make fast progress.  But I don't have a timeframe.

Please, keep the feedback coming.  Would you be interested in being one of our early testers when we have composer working?

**Comment by KLVTZ** [comment]
@markkelnar Thanks for providing some feedback! I'm really happy to hear that this issue has been discussed and there are those like you who are striving to make this workflow better. We would love to be one of the early testers for composer support! 

For reference, I work alongside TEN: The Enthusiast Network and develop under their tenpoc account. 

We look forward to this!

**Comment by markkelnar** [comment]
Ok.  Thanks again.
