### ISSUE TITLE
Warning about downloading s3-uploads while provisioning after doing vagrant reload 

### ISSUE THREAD

**Issue by aaronware** [wpengine/hgv#240]
```
==> mercuryvagrant: TASK: [wordpress | Install useful plugins from VCS repos for property] ******** 
==> mercuryvagrant: failed: [127.0.0.1] => (item={'url': 'https://github.com/humanmade/S3-Uploads/archive/v0.9.0.zip', 'slug': 'S3-Uploads-0.9.0'}) => {"changed": true, "cmd": ["/usr/local/bin/wp", "plugin", "install", "https://github.com/humanmade/S3-Uploads/archive/v0.9.0.zip"], "delta": "0:00:01.895225", "end": "2015-09-20 18:25:07.386864", "item": {"slug": "S3-Uploads-0.9.0", "url": "https://github.com/humanmade/S3-Uploads/archive/v0.9.0.zip"}, "rc": 255, "start": "2015-09-20 18:25:05.491639", "warnings": []}
```

**Comment by aaronware** [comment]
Only had this happen out of 1 install which I thought was strange. I have about 10 individually provisioned installs.

**Comment by ericmann** [comment]
Unfortunately, there's nothing in the log there that indicates _why_ the install failed, just that it failed. Since this only happened on 1 install out of the 10 you have, my best guess is that it was an intermittent timeout with GitHub (since the provisioner attempts to download a fresh zip).

We can add some further retries around this step in the provisioning, but unless it becomes a more persistent issue that might be premature.

I'm closing for now, but if this comes up again feel free to re-open it.

**Comment by aaronware** [comment]
Totally fine with the close. I honestly haven't seen it happen again and I've provisioned multiple sites using 1.3,1.4 and 1.5 since then
