### ISSUE TITLE
VirtualBox 5.0 support

### ISSUE THREAD

**Issue by elimc** [wpengine/hgv#260]
I was following the instructions to setting up hgv, and I received an error while doing `vagrant up --provider=virtualbox`:

```
The provider 'virtualbox' that was requested to back the machine
'mercury_vagrant' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

Now, this is a great error message, and I'm not being sarcastic, but there isn't any notice in the documentation that VirtualBox 4.0 is required. In fact, the documentation sends people to a link where they will download VirtualBox 5.0. It would probably be a good idea to give a notice to people about how to set up hgv, properly, until hgv has support for VB 5.0.

**Update:** I wasn't interested in downgrading VB, and I figured there wouldn't be any compatibility issues, so I navigated to `script/lib/preflight.js` and changed the VirtualBox dependency to 5.0. It works perfectly. Something to think about.

**Comment by zamoose** [comment]
What version of Vagrant are you running? That message is generated by
Vagrant, not by HGV proper.

On Wed, Oct 14, 2015 at 10:12 PM, Eli McMakin <notifications@github.com>
wrote:

> I was following the instructions to setting up hgv, and I received an
> error while doing vagrant up --provider=virtualbox:
>
> The provider 'virtualbox' that was requested to back the machine
> 'mercury_vagrant' is reporting that it isn't usable on this system. The
> reason is shown below:
>
> Vagrant has detected that you have a version of VirtualBox installed
> that is not supported. Please install one of the supported versions
> listed below to use Vagrant:
>
> 4.0, 4.1, 4.2, 4.3
>
> Now, this is a great error message, and I'm not being sarcastic, but there
> isn't any notice in the documentation that VirtualBox 4.0 is required. In
> fact, the documentation sends people to a link where they will download
> VirtualBox 5.0. It would probably be a good idea to give a notice to people
> about how to set up hgv, properly, until hgv has support for VB 5.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/issues/260>.
>



-- 
-Doug

**Comment by elimc** [comment]
Vagrant 1.7.4

**Comment by ericmann** [comment]
@elimc There are a couple of things going on here, and I want to address them before I close just so you know what's happening.

**First**, the error message you were seeing was a Vagrant-VirtualBox issue. It had nothing to do with HGV itself and, actually, would have affected _any_ virtual machines you had on your machine. I recently upgraded to VirtualBox 5.0.6 and faced the exact same error message. At the time, thought, I was running Vagrant 1.7.2.

Upgrading to 1.7.4 fixed the issue. If you were on 1.7.4 already, then I suspect it was an intermittent issue.

**Second**, the preflight script has nothing to do with provisioning. It's a diagnostic tool we use to test the _minimum_ requirements against your system. The _minimum_ supported version of VirtualBox is still 4.3.20. Changing anything in the preflight script won't change that because, again, all the script does is scan your system and report whether or not your installed VirtualBox version is supported.

This all being said, I want to thank you for raising this issue here ... but it's not a bug with HGV or something we can fix on our end.
