### ISSUE TITLE
wpengine.com/mercury link is "dead"

### ISSUE THREAD

**Issue by tavon** [wpengine/hgv#297]
@asmartbear, @markkelnar 

http://wpengine.com/mercury link redirects to the /enterprise page.  

A support agent stated that the page was pulled, implying that the project was no longer being supported by WPEngine.  Something about the server configuration is no longer being used at WPEngine.

Is this the case?  Is WPEngine no longer supporting hgv/mercury?

**Comment by asmartbear** [comment]
Hi John, what we determined as the project went on, is that while HHVM has
immediate speed benefits, it has serious uptime issues which even very
technical developers (at major WordPress agencies you've heard of) were not
able to or willing to manage.

On top of that, PHP7 emerged as something that was clearly going to match
HHVM in speed except drastically exceed it in compatibility and uptime, so
although the full timeline of that being practical for WordPress was
unknown, it was the correct long-term bet for ourselves and for our
customers.

Because of those two things, we decided to stop the Mercury platform and
instead invest in an exciting new platform which is under way today but
which we're keeping under wraps for the time being.

Having said that, the confusingly-named "Mercury Vagrant" project, or HGV,
*does* continue to be maintained and advanced.  That's the fully-GPL
project which we did for the community and is available on github.  We
probably should rename it so the distinction is clear!

Thanks for your interest and please let me know how else we can be helpful!

**Comment by tavon** [comment]
Hi Jason/@asmartbear,

Thank you for the quick response.

As a WPEngine customer, I'm not concerned with PHP7 vs HHVM but more interested in creating a local multisite development environment.  HGV has been a perfect solution.  Along side with Git deploy and a couple plugins to pull down the production database / files, this project has been the best solution we've found so far.  It almost rivals my Ruby on Rails deployment environments. Not quite but close.

Is it foolish to depend on this project as a Wordpress/Multisite development workflow/environment supported by WPEngine?

**Comment by asmartbear** [comment]
Hi John, please do continue to do that!  As I said, we're committed to HGV,
and in any case it's GPL so there's no way for us to "stop" the project.

What we stopped doing is supporting the similarly-named platform that we
host, called Mercury.

Thanks for the kind words!

**Comment by tavon** [comment]
Thanks again!
