### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by webgurus** [wpengine/hgv#319]
Hello,

It seems that issues are not getting fixed and comments not being replied to. Could you confirm if this project is still alive?

Thanks,
Marton

**Comment by arnoldsandoval** [comment]
+1

**Comment by asher-yoyoyo** [comment]
+10

**Comment by cwonrails** [comment]
+100

**Comment by andrew40** [comment]
It doesn't look like this is being actively developed any further as there has been no answers from developers or WP Engine. All the Mercury pages on WP Engine now default to WP Engine enterprise.

I have to be honest, I used to love WP Engine and had numerous large installs with them which I have slowly started moving away, due the very poor technical support on chat. It is always assumed it is your fault, and 'please consult your developer' type comments when your the damned developer. Its never their issue, and 90% of the time it is them thats ballsed something up. It has gone downhill very recently, which is usual when companies grow, get big and can't handle their customers technical queries.

When one says " I suggest you do this . . ." DONT DO IT!

**Comment by andrew40** [comment]
Please see attached screenshot.. from a recent chat with WP Engine

Andrew, it seems that we are not developing or supporting Mercury Vagrant at this time. I'm curious, what project are you working on?

![screenshot 2016-10-27 13 27 34](https://cloud.githubusercontent.com/assets/158435/19767120/3894ae34-9c49-11e6-995b-65398c6a0e29.png)

**Comment by zamoose** [comment]
I've started work on a fork of sorts over here: https://github.com/zamoose/chgv. It's based on CentOS instead of Ubuntu, if that floats your boat.

 It's in its early stages, but I'm using a lot of the concepts started here in HGV and adding some other best practices that I've picked up along the way. It's not ready for release, but if you want to help out and/or take advantage of it, be my guest. *grin* Pull requests wanted!

**Comment by morganmccol** [comment]
What is the next best alternative to this project if it's no longer viable?

Are most people switching to something like [php7dev](https://github.com/rlerdorf/php7dev)?

**Comment by andrew40** [comment]
I started using Trellis by the people at Roots. Very impressed with it so far, if a little difficult to get it started, but its the whole development cycle from dev - staging - live, so you have to set all three up for it to work correctly..

https://github.com/roots/trellis

**Comment by jshwlkr** [comment]
Is there a reason no one's mentioned [https://github.com/Varying-Vagrant-Vagrants/VVV](https://github.com/Varying-Vagrant-Vagrants/VVV)? (Other than just not knowing it exists.)

**Comment by ehoanshelt** [comment]
Hey folks!

This project is very much alive. We're so sorry that we haven't been keeping this up to date. Currently, the master branch has shown successful builds within our testing now that we've merged additional fixes. We're also actively working on additional updates to bring the rest of the vagrant up to date so stay tuned!

Please feel free to report any additional issues that you may find and we'll make sure we tackle them as soon as we can!

Thanks for your understanding! I'm going to close this issue for now so that we don't cause confusion.
