### ISSUE TITLE
.dev TLD interference

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#98]
As per this VVV issue, Google has applied for ownership of the .dev TLD:

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583

This is problematic and should probably be routed around well in advance. 

@markkelnar @stephen-lin thoughts?

**Comment by zamoose** [comment]
(My preference would be .test or .localhost).

**Comment by stephen-lin** [comment]
My vote would be for .test.

**Comment by markkelnar** [comment]
I'm ok with changing this to avoid conflict, agree .test or .localhost.  And since we're shoving the IPs in /etc/hosts, requests should still resolve to the vagrant.

**Comment by michaelbeil** [comment]
.test is shorter and simpler and would be my preference.

any qualms on using .hgv?

**Comment by zamoose** [comment]
Just that it's not guaranteed to never be stomped upon at a later date.

On Mon, Apr 6, 2015 at 10:47 AM, Michael Beil <notifications@github.com>
wrote:

> .test is shorter and simpler and would be my preference.
>
> any qualms on using .hgv?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/issues/98#issuecomment-90085110>.
>



-- 
-Doug

**Comment by michaelbeil** [comment]
my thoughts exactly. you should claim it @zamoose :D.

**Comment by rcjohnson** [comment]
Since .test is never supposed to be claimed as a TLD (http://en.wikipedia.org/wiki/.test) my vote is for .test.

**Comment by michaelbeil** [comment]
+1 @rcjohnson.

**Comment by ericmann** [comment]
I do like how short `.test` is as a default, but as it's 4 chars instead of the usual 3 it will make DB search-and-replace a bit problematic (at least with serialized data).  Using `.dev` made life easy as it was a 1:1 replacement for `.com`, `.org`, `.net` and the like.

Granted, this doesn't solve for sites with 2-char TLDs, but they're still in the minority. Still, switching to a 4-char dev TLD will make migrating content from development to production that much more difficult.

I'd lean towards `.hgv` for this reason. No guarantee someone won't stomp it in the future, but in the "now" it's an easier alternative.

**Comment by rcjohnson** [comment]
I think the .test is the best approach so that we don't introduce a collision going forwards. WP CLI handles the .com to .test find/replace well, even with serialized data. I'd say let's introduce the .test domains in 1.3 and we can deprecate the .dev domains in a future release to give people time to switch their processes.
